E-Ticket/Models/Movie.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;


namespace E_Ticket.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        [Range(1, 10000)]
        public double Price { get; set; }
        [ValidateNever]
        public string? ImgUrl { get; set; } = "default.jpg";
        public string TrailerUrl { get; set; }

        public DateTime StartDate { get; set; }
        [CustomValidation(typeof(Movie), "ValidateStartEndDate")]
        public DateTime EndDate { get; set; }

        [Required]
        public MovieStatus MovieStatus { get; set; }
        [Range(0, int.MaxValue)]
        public int TotalTickets { get; set; }
        [Range(0, int.MaxValue)]
        public int TicketsSold { get; set; }
        public int TicketsRemaining => TotalTickets - TicketsSold;


        public int CategoryId { get; set; } 
        

        [ValidateNever]
        public Category Category { get; set; }
        [ValidateNever] 
        public ICollection<CinemaMovie> CinemaMovies { get; set; }
        [ValidateNever]
        public ICollection<ActorMovie> ActorMovies { get; set; }
        [ValidateNever]
        public ICollection<Ticket> Tickets { get; set; }
        [ValidateNever]
        public ICollection<OrderList> OrderLists { get; set; }


        public static ValidationResult ValidateStartEndDate(DateTime endDate, ValidationContext context)
        {
            var instance = context.ObjectInstance as Movie;
            if (instance == null || instance.StartDate <= endDate)
            {
                return ValidationResult.Success;
            }
            return new ValidationResult("End Date must be after Start Date.");
        }

    }

    public enum MovieStatus
    {
        Upcoming,
        Available,
        Expired,
    }
}

E-Ticket/Areas/Admin/Controllers/DashboardController.cs
using E_Ticket.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
namespace E_Ticket.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        [Area("Admin")]
        [Authorize(Roles = SD.AdminRole)]
        public IActionResult Index()
        {
            return View();
        }


    }
}

E-Ticket/Areas/Admin/Controllers/MovieController.cs
using E_Ticket.Models;
using E_Ticket.Repository;
using E_Ticket.Repository.IRepository;
using E_Ticket.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;

namespace E_Ticket.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.AdminRole)]
    public class MovieController : Controller
    {
        private readonly IMovieRepository movieRepository;
        private readonly ICategoryRepository categoryRepository;
        private readonly ICinemaRepository cinemaRepository;
        private readonly IRepository<CinemaMovie> cinemaMovieRepository;
        private readonly IRepository<ActorMovie> actorMovieRepository;
        private readonly IActorRepository actorRepository;
        private readonly ILogger<MovieController> logger;

        public MovieController(IMovieRepository movieRepository, ICategoryRepository categoryRepository,
            ICinemaRepository cinemaRepository, IRepository<CinemaMovie> CinemaMovieRepository,
            IRepository<ActorMovie> actorMovieRepository, IActorRepository actorRepository, ILogger<MovieController> logger)
        {
            this.movieRepository = movieRepository;
            this.categoryRepository = categoryRepository;
            this.cinemaRepository = cinemaRepository;
            cinemaMovieRepository = CinemaMovieRepository;
            this.actorMovieRepository = actorMovieRepository;
            this.actorRepository = actorRepository;
            this.logger = logger;
        }


        public IActionResult Index(string? Name = null, int pageNumber = 1)
        {
            IEnumerable<Movie> movies;
            if (Name == null)
                movies = movieRepository.Get(include: [c => c.Category]);
            else
                movies = movieRepository.Get(include: [c => c.Category], where: e => e.Name.Contains(Name));

            if (!movies.Any())
            {
                TempData["NotFound"] = "Sorry we cant found the Movie try again";
                return RedirectToAction("MovieCRUD");
            }

            int itemsNum = 8;
            int totalMovies = movies.Count();
            int totalPages = (int)Math.Ceiling(totalMovies / (double)itemsNum);

            if (pageNumber < 1)
                pageNumber = 1;
            else if (pageNumber > totalPages)
                return RedirectToAction("NotFound", "Errors");

            ViewBag.pageNumber = pageNumber;
            ViewBag.totalPages = totalPages;

            return View(movies.Skip((pageNumber - 1) * itemsNum).Take(itemsNum));
        }

        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(categoryRepository.Get(), "Id", "Name");
            ViewBag.Cinemas = new SelectList(cinemaRepository.Get(), "Id", "Name");
            ViewBag.MovieStatuses = new SelectList(Enum.GetValues(typeof(MovieStatus)));

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Movie movie, List<int> CinemasList, IFormFile PhotoUrl)
        {
            ModelState.Remove(nameof(PhotoUrl));
            ModelState.Remove(nameof(CinemasList));
            if (ModelState.IsValid)
            {
                if (movie.MovieStatus == MovieStatus.Expired)
                {
                    movie.TotalTickets = 0;
                    movie.TicketsSold = 0;
                }
                movieRepository.CreateWithImage(movie, PhotoUrl, "movies", "ImgUrl");
                Log(nameof(Create), nameof(movie));

                foreach (var item in CinemasList)
                {
                    cinemaMovieRepository.Create(new CinemaMovie { CinemaId = item, MovieId = movie.Id });
                    cinemaMovieRepository.Commit();
                }

                return RedirectToAction("Index");
            }
            return RedirectToAction("SomeThingWrong", "Errors");
        }


        public IActionResult Edit(int movieId)
        {
            ViewBag.Categories = new SelectList(categoryRepository.Get(), "Id", "Name");
            ViewBag.Cinemas = new SelectList(cinemaRepository.Get(), "Id", "Name");
            ViewBag.MovieStatuses = new SelectList(Enum.GetValues(typeof(MovieStatus)));
            var movie = movieRepository.GetDetails(movieId);



            var selectedCinemas = movie.CinemaMovies.Select(cm => cm.CinemaId).ToList();
            ViewBag.SelectedCinemas = selectedCinemas;

            return View(movie);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Movie movie, List<int> CinemasList, IFormFile PhotoUrl)
        {
            ModelState.Remove(nameof(PhotoUrl));
            ModelState.Remove(nameof(CinemasList));
            if (ModelState.IsValid)
            {
                var oldMovie = movieRepository.GetOne(where: e => e.Id == movie.Id);
                if (movie.MovieStatus == MovieStatus.Expired)
                {
                    movie.TotalTickets = 0;
                    movie.TicketsSold = 0;

                }
                movieRepository.UpdateImage(movie, PhotoUrl, oldMovie.ImgUrl, "movies", "ImgUrl");
                Log(nameof(Edit), nameof(movie));

                var toDelete = cinemaMovieRepository.Get(where: e => e.MovieId == movie.Id, tracked: false);
                if (toDelete != null)
                {
                    foreach (var item in toDelete)
                    {
                        cinemaMovieRepository.Delete(item);
                    }
                }

                foreach (var cinemaId in CinemasList)
                {
                    cinemaMovieRepository.Create(new CinemaMovie { CinemaId = cinemaId, MovieId = movie.Id });
                }
                cinemaMovieRepository.Commit();
                return RedirectToAction("Index");
            }
            return RedirectToAction("SomeThingWrong", "Errors");
        }

        public IActionResult Delete(int movieId)
        {
            var movie = movieRepository.GetDetails(movieId);
            return View(movie);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Movie movie)
        {
            var cinemaToDelete = cinemaMovieRepository.Get(where: e => e.MovieId == movie.Id, tracked: false);
            if (cinemaToDelete != null)
            {
                foreach (var cinema in cinemaToDelete)
                {
                    cinemaMovieRepository.Delete(cinema);
                }
            }

            var actorToDelete = actorMovieRepository.Get(where: e => e.MovieId == movie.Id, tracked: false);
            if (actorToDelete != null)
            {
                foreach (var actor in actorToDelete)
                {
                    actorMovieRepository.Delete(actor);
                }
            }

            Log(nameof(Delete), nameof(movie));

            movieRepository.Delete(movie);
            movieRepository.Commit();
            return RedirectToAction("Index");
        }



        public IActionResult AssignActor(int movieId)
        {
            var movie = movieRepository.GetDetails(movieId);

            var allActors = actorRepository.Get().ToList();
            var assignedActors = movie.ActorMovies.Select(am => am.ActorId).ToList();

            ViewBag.AllActors = new SelectList(allActors, "Id", "FullName");
            ViewBag.AssignedActors = assignedActors;

            return View(movie);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AssignActor(int Id, List<int> AssignedActors)
        {
            var movie = movieRepository.GetOne(where: w => w.Id == Id);

            if (movie == null)
            {
                return NotFound();
            }
            var toDelete = actorMovieRepository.Get(where: e => e.MovieId == movie.Id, tracked: false);
            if (toDelete != null)
            {
                foreach (var item in toDelete)
                {
                    actorMovieRepository.Delete(item);
                }
            }

            foreach (var actorId in AssignedActors)
            {
                actorMovieRepository.Create(new ActorMovie { ActorId = actorId, MovieId = movie.Id });
            }

            Log(nameof(AssignActor), nameof(movie));
            actorMovieRepository.Commit();

            return RedirectToAction("Index");
        }




        public byte[] ExportMoviesToExcel(IEnumerable<Movie> movies)
        {
            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("Movies");

                // Add headers
                worksheet.Cells[1, 1].Value = "Name";
                worksheet.Cells[1, 2].Value = "Description";
                worksheet.Cells[1, 3].Value = "Price";
                worksheet.Cells[1, 4].Value = "Img Url";
                worksheet.Cells[1, 5].Value = "TrailerUrl";
                worksheet.Cells[1, 6].Value = "StartDate";
                worksheet.Cells[1, 7].Value = "EndDate";
                worksheet.Cells[1, 8].Value = "MovieStatus";
                worksheet.Cells[1, 9].Value = "TotalTickets";
                worksheet.Cells[1, 10].Value = "TicketsSold";
                worksheet.Cells[1, 11].Value = "CategoryId";
                worksheet.Cells[1, 12].Value = "CategoryName";
                worksheet.Cells[1, 13].Value = "ActorsId";
                worksheet.Cells[1, 14].Value = "ActorsNames";
                worksheet.Cells[1, 15].Value = "CinemasId";
                worksheet.Cells[1, 16].Value = "CinemasNames";

                int row = 2;
                foreach (var movie in movies)
                {
                    worksheet.Cells[row, 1].Value = movie.Name;

E-Ticket/Areas/Admin/Views/Movie/AssignActor.cshtml
@model Movie

<div class="card mb-3 pb-4" style="max-width: 100%;">
    <div class="row g-0">
        <div class="card-header">
            <h5 class="card-title">@Model.Name</h5>
        </div>
        <div class="col-md-4">
            <img src="~/images/movies/@Model.ImgUrl" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">Movie details:</h5>
                <p class="card-text">@Model.Description</p>
            </div>


            <form asp-action="AssignActor" method="post" class="m-2">
                <input type="hidden" asp-for="Id" />

                <div class="form-group ">
                    <label>Actors:- </label>
                    <div class="cards-wrap justify-content-md-start " style="max-height:50%; ">
                        @foreach (var actor in ViewBag.AllActors)
                        {
                            int actorId;
                            if (int.TryParse(actor.Value, out actorId))
                            {
                                <div class="form-check m-1">
                                    <input type="checkbox" class="form-check-input" id="actor_@actor.Value" name="AssignedActors" value="@actor.Value" @(ViewBag.AssignedActors.Contains(actorId) ? "checked" : "") />
                                    <label class="form-check-label" for="actor_@actor.Value">@actor.Text</label>
                                    <hr />
                                </div>
                            }
                        }
                    </div>
                </div>
                <button type="submit" class="btn btn-primary w-100">Save</button>

            </form>



        </div>
    </div>
</div>

E-Ticket/Areas/Admin/Views/Movie/Create.cshtml
@model Movie


@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var Categories = ViewBag.Categories as SelectList;
    var cinemaList = ViewBag.Cinemas as SelectList;
}

<h1>Create</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImgUrl" class="control-label"></label>
                <input asp-for="ImgUrl" class="form-control" type="file" name="PhotoUrl" />
                <span asp-validation-for="ImgUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrailerUrl" class="control-label"></label>
                <input asp-for="TrailerUrl" class="form-control" />
                <span asp-validation-for="TrailerUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieStatus" class="control-label"></label>
                <select asp-for="MovieStatus" class="form-control" asp-items="ViewBag.MovieStatuses"></select>
                <span asp-validation-for="MovieStatus" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                @foreach (var cinema in cinemaList)
                {
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="cinema_@cinema.Value" name="CinemasList" value="@cinema.Value" />
                        <label class="form-check-label" for="cinema_@cinema.Value">@cinema.Text</label>
                    </div>
                }

            </div>

            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="Categories"></select>
            </div>

            <div class="form-group">
                <label asp-for="TotalTickets" class="control-label"></label>
                <input asp-for=" TotalTickets" class="form-control" />
                <span asp-validation-for="TotalTickets" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" /> |
                <a asp-controller="Dashboard" asp-action="MovieCRUD" class="btn btn-outline-light">Back to List</a>
            </div>
        </form>
    </div>
</div>

<div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

E-Ticket/Areas/Admin/Views/Movie/Delete.cshtml
@model E_Ticket.Models.Movie

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImgUrl)
        </dt>
        <dd class="col-sm-10">

            <img src="~/images/movies/@Html.DisplayFor(model => model.ImgUrl)" class="actors-img " alt="Alternate Text" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TrailerUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TrailerUrl)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MovieStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MovieStatus)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TotalTickets)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TotalTickets)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TicketsSold)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TicketsSold)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt class="col-sm-2">
            Cinemas 
        </dt>
        <dd class="col-sm-10">
            @foreach (var cinemaMovie in Model.CinemaMovies)
            {
                <span>
                    @cinemaMovie.Cinema.Name /

                </span>
            }
        </dd>

    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

E-Ticket/Areas/Admin/Views/Movie/Edit.cshtml
@model E_Ticket.Models.Movie

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var Categories = ViewBag.Categories as SelectList;
    var cinemaList = ViewBag.Cinemas as SelectList;
    var selectedCinemas = ViewBag.SelectedCinemas as List<int>;
}

<h1>Edit</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImgUrl" class="control-label"></label>
                <input asp-for="ImgUrl" class="form-control" type="file" name="PhotoUrl" data-val="false"/>
                <span asp-validation-for="ImgUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrailerUrl" class="control-label"></label>
                <input asp-for="TrailerUrl" class="form-control" />
                <span asp-validation-for="TrailerUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieStatus" class="control-label"></label>
                <select asp-for="MovieStatus" class="form-control" asp-items="ViewBag.MovieStatuses"></select>
                <span asp-validation-for="MovieStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalTickets" class="control-label"></label>
                <input asp-for="TotalTickets" class="form-control" />
                <span asp-validation-for="TotalTickets" class="text-danger"></span>
            </div>
            <input type="hidden" value="@Model.TicketsSold" name="TicketsSold" />
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="Categories"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>



            <div class="form-group">
                @foreach (var cinema in cinemaList)
                {
                    int cinemaId;
                    if (int.TryParse(cinema.Value, out cinemaId))
                    {
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="cinema_@cinema.Value" name="CinemasList" value="@cinema.Value" @(selectedCinemas.Contains(cinemaId) ? "checked" : "") />
                            <label class="form-check-label" for="cinema_@cinema.Value">@cinema.Text</label>
                        </div>
                    }
                }
            </div>


            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

E-Ticket/Areas/Admin/Views/Movie/Index.cshtml
@model IEnumerable<E_Ticket.Models.Movie>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="d-flex justify-content-between">
    <h1>Index</h1>
    <h1 class="text-center"><a href="/Admin/Dashboard/index"><i class="bi bi-arrow-left-circle" style="color:#2c377d;"></i> </a> </h1>
</div>
<hr />

<p class="flex-column">
    <form asp-action="Index" method="get" class="d-flex">
        <div class="col-2">
            <a asp-action="Create" class="btn btn-outline-light ">Create New</a>
        </div>
        <input type="text" class="form-control me-3" id="movieSearch" name="Name" aria-label="Search for movie..." placeholder="Search for movie..." required />
        <button type="submit" class="btn btn-light"><i class="bi bi-search"></i></button>
    </form>
</p>
<hr />
@if (TempData["NotFound"] != null)
{
    <div class="error-inner ">
        <h1 class="text-center reglar-text" style="font-size:6rem;"><i class="bi bi-patch-exclamation"></i></h1>
    </div>
    <h3 class="text-center reglar-text">@TempData["NotFound"]</h3>
    <hr />
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImgUrl)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MovieStatus)
            </th>
            <th style="width:10%;">
                Total || Sold
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <img src="~/images/movies/@Html.DisplayFor(modelItem => item.ImgUrl)" class="actors-img " alt="Alternate Text" />
                </td>
               
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MovieStatus)
                </td>
                <td>
                    T: @Html.DisplayFor(modelItem => item.TotalTickets)
                    ||
                    S: @Html.DisplayFor(modelItem => item.TicketsSold)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-movieId="@item.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-movieId="@item.Id">Delete</a>|
                    <a asp-action="AssignActor" asp-route-movieId="@item.Id">Actors</a>
                </td>
            </tr>
        }
    </tbody>
</table>


<div>
    <hr />
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center mt-3">
            <li class="page-item @(ViewBag.pageNumber <= 1 ? "disabled":"")">
                <a class="page-link" href="?pageNumber=@(ViewBag.pageNumber - 1)" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            @for (int i = 1; i <= ViewBag.totalPages; i++)
            {
                <li class="page-item @(i == ViewBag.pageNumber ? "active" : "")">
                    <a class="page-link" href="?pageNumber=@i">@i</a>
                </li>
            }
            <li class="page-item @(ViewBag.pageNumber >= ViewBag.totalPages ? "disabled" : "")">
                <a class="page-link" href="?pageNumber=@(ViewBag.pageNumber + 1)" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

E-Ticket/Areas/Admin/Views/Movie/UploadExcel.cshtml
<div class="justify-content-center align-content-center">
    <form asp-action="UploadExcel" method="post" enctype="multipart/form-data">
        <label for="file">Upload Excel File</label>
        <input id="file" class="form-control" type="file" name="file"  />
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>

</div>