E-Ticket/Models/ActorMovie.cs
namespace E_Ticket.Models
{
    public class ActorMovie
    {
        public int ActorId { get; set; }
        public Actor Actor { get; set; }
        public int MovieId { get; set; }
        public Movie Movie { get; set; }
    }
}

E-Ticket/Areas/Admin/Controllers/ActorController.cs
using E_Ticket.Models;
using E_Ticket.Repository.IRepository;
using E_Ticket.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace E_Ticket.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.AdminRole)]
    public class ActorController : Controller
    {
        private readonly IActorRepository actorRepository;
        private readonly ILogger<ActorController> logger;

        public ActorController(IActorRepository actorRepository,ILogger<ActorController> logger)
        {
            this.actorRepository = actorRepository;
            this.logger = logger;
        }

        public IActionResult Index(string? Name = null, int pageNumber = 1)
        {
            IEnumerable<Actor> actors;
            if (Name == null)
                actors = actorRepository.Get(include: [a=>a.ActorMovies]);
            else
                actors = actorRepository.Get(include: [a => a.ActorMovies], 
                    where: e=>e.FirstName.Contains(Name) || e.LastName.Contains(Name));

            if (!actors.Any())
            {
                TempData["NotFound"] = "Sorry we cant found the Actor try again";
                return RedirectToAction("Index");
            }
            int itemsNum = 8;
            int totalMovies = actors.Count();
            int totalPages = (int)Math.Ceiling(totalMovies / (double)itemsNum);
            if (pageNumber < 1)
                pageNumber = 1;
            else if (pageNumber > totalPages)
                return RedirectToAction("NotFound", "Errors");

            ViewBag.pageNumber = pageNumber;
            ViewBag.totalPages = totalPages;


            return View(actors.Skip((pageNumber - 1) * itemsNum).Take(itemsNum));
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Actor actor, IFormFile PhotoUrl)
        {
            ModelState.Remove(nameof(PhotoUrl));
            if (ModelState.IsValid)
            {
                actorRepository.CreateWithImage(actor, PhotoUrl, "cast", "ProfilePicture");

                Log(nameof(Create), nameof(actor));

                return RedirectToAction("Index");

            }
            return RedirectToAction("SomeThingWrong", "Errors");
        }

        public IActionResult Edit(int actorId)
        {
            var actor = actorRepository.GetOne(where: e=>e.Id == actorId);
            return View(actor);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Actor actor, IFormFile PhotoUrl)
        {
            ModelState.Remove(nameof(PhotoUrl));
            if (ModelState.IsValid)
            {
                var oldActor = actorRepository.GetOne(where: e => e.Id == actor.Id , tracked: false);
                actorRepository.UpdateImage(actor, PhotoUrl, oldActor.ProfilePicture, "cast", "ProfilePicture");
                
                Log(nameof(Edit), nameof(actor));

                return RedirectToAction("Index");
            }
            return RedirectToAction("SomeThingWrong", "Errors");
        }
        public IActionResult Delete(int actorId)
        {
            var actor = actorRepository.GetOne(where: e => e.Id == actorId);
            return View(actor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Actor actor)
        {
            actorRepository.Delete(actor);
            Log(nameof(Delete),nameof(actor));
            return RedirectToAction("Index");
        }


        public void Log(string action , string entity)
        {
            var admin = User.Identity.Name;
            LoggerHelper.LogAdminAction(logger, admin, action, entity);
        }


    }
}

E-Ticket/Areas/Admin/Controllers/CinemaController.cs
using E_Ticket.Models;
using E_Ticket.Repository.IRepository;
using E_Ticket.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace E_Ticket.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.AdminRole)]
    public class CinemaController : Controller
    {
        private readonly ICinemaRepository cinemaRepository;
        private readonly ILogger<CinemaController> logger;

        public CinemaController(ICinemaRepository cinemaRepository,ILogger<CinemaController> logger)
        {
            this.cinemaRepository = cinemaRepository;
            this.logger = logger;
        }

        public IActionResult Index()
        {
            var cinemas = cinemaRepository.Get();
            return View(cinemas);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Cinema cinema)
        {
            if (ModelState.IsValid)
            {
                cinemaRepository.Create(cinema);
                cinemaRepository.Commit();
                Log(nameof(Create), nameof(cinema));
                return RedirectToAction("Index");
            }
            return RedirectToAction("SomeThingWrong", "Errors");
        }

        public IActionResult Edit(int cinemaId)
        {
            var cinema = cinemaRepository.GetOne(where: e=>e.Id == cinemaId);
            return View(cinema);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Cinema cinema)
        {
            if (ModelState.IsValid)
            {
                cinemaRepository.Update(cinema);
                cinemaRepository.Commit();
                Log(nameof(Edit), nameof(cinema));
                return RedirectToAction("Index");
            }
            return RedirectToAction("SomeThingWrong", "Errors");

        }

        public IActionResult Delete(int cinemaId)
        {
            var cinema = cinemaRepository.GetOne(where: e=>e.Id == cinemaId);
            return View(cinema);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Cinema cinema)
        {
            cinemaRepository.Delete(cinema);
            cinemaRepository.Commit();
            Log(nameof(Delete), nameof(cinema));
            return RedirectToAction("Index");
        }


        public void Log(string action, string entity)
        {
            var admin = User.Identity.Name;
            LoggerHelper.LogAdminAction(logger, admin, action, entity);
        }

    }
}

E-Ticket/Areas/Customer/Controllers/HomeController.cs
using E_Ticket.Models;
using E_Ticket.Repository;
using E_Ticket.Repository.IRepository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace E_Ticket.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMovieRepository movieRepository;
        private readonly ICategoryRepository categoryRepository;
        private readonly ICinemaRepository cinemaRepository;
        private readonly IRepository<CinemaMovie> cinemaMovieRepository;
        private readonly IRepository<Actor> actorRepository;
        private readonly IRepository<ActorMovie> actorMovieRepository;
        private readonly UserManager<IdentityUser> userManager;
        private readonly IRepository<Wishlist> wishlistRepository;

        public HomeController(ILogger<HomeController> logger, IMovieRepository movieRepository,
            ICategoryRepository categoryRepository, ICinemaRepository cinemaRepository,
            IRepository<CinemaMovie> cinemaMovieRepository, IRepository<Actor> actorRepository,
            IRepository<ActorMovie> actorMovieRepository,
            UserManager<IdentityUser> userManager, IRepository<Wishlist> wishlistRepository)
        {
            _logger = logger;
            this.movieRepository = movieRepository;
            this.categoryRepository = categoryRepository;
            this.cinemaRepository = cinemaRepository;
            this.cinemaMovieRepository = cinemaMovieRepository;
            this.actorRepository = actorRepository;
            this.actorMovieRepository = actorMovieRepository;
            this.userManager = userManager;
            this.wishlistRepository = wishlistRepository;
        }

        public async Task<IActionResult> Index(int pageNumber = 1)
        {
            int itemsNum = 8;
            int totalMovies = movieRepository.Get().Count();
            int totalPages = (int)Math.Ceiling(totalMovies / (double)itemsNum);
            if (pageNumber < 1)
                pageNumber = 1;
            else if (pageNumber > totalPages)
                return RedirectToAction("NotFound", "Errors");

            await SetUserWishlist();

            var movies = movieRepository.Get([q => q.Category]).Skip((pageNumber - 1) * itemsNum).Take(itemsNum);

            ViewBag.pageNumber = pageNumber;
            ViewBag.totalPages = totalPages;

            return View(movies);
        }

        public async Task<IActionResult> Details(int movieId)
        {
            var movie = movieRepository.GetDetails(movieId);
            if (movie != null)
            {
                await SetUserWishlist();
                return View(movie);
            }
            return RedirectToAction("NotFound", "Errors");
        }

        [HttpGet]
        // To get the search list with the JS to work 
        public JsonResult SearchMovies(string name)
        {
            var movies = movieRepository.SearchMovies(name)
                       .Select(m => new { m.Id, m.Name, m.ImgUrl })
                       .Take(3) // Show only the first 3 results
                       .ToList();
            return Json(movies);
        }

        [HttpPost]
        public async Task<IActionResult> Search(string Name)
        {
            await SetUserWishlist();

            var movies = movieRepository.SearchMovies(Name);
            if (movies.Any())
            {
                return View(movies);
            }
            else
            {
                return RedirectToAction("SearchNotFound", "Errors");
            }
        }

        public IActionResult Categories()
        {
            var categories = categoryRepository.Get();
            return View(categories);
        }

        public IActionResult CategoryMovies(int categoryId, int pageNumber = 1)
        {
            if (categoryId != 0)
            {
                Response.Cookies.Append("CategoryId", categoryId.ToString());
            }
            if (categoryId == 0)
            {
                categoryId = int.Parse(Request.Cookies["CategoryId"]);
            }

            int itemsNum = 4;
            int totalMovies = movieRepository.Get(include: [c => c.Category],
                where: e => e.CategoryId == categoryId).Count();
            int totalPages = (int)Math.Ceiling(totalMovies / (double)itemsNum);
            if (pageNumber < 1)
                pageNumber = 1;
            else if (pageNumber > totalPages)
                return RedirectToAction("NotFound", "Errors");

            ViewBag.pageNumber = pageNumber;
            ViewBag.totalPages = totalPages;

            var movies = movieRepository.Get(include: [c => c.Category],
                where: e => e.CategoryId == categoryId)
                .Skip((pageNumber - 1) * itemsNum).Take(itemsNum);

            return View(movies);
        }


        public IActionResult Cinemas()
        {
            var cinemas = cinemaRepository.Get();
            return View(cinemas);
        }

        public IActionResult CinemaMovies(int CinemaId, int pageNumber = 1)
        {
            if (CinemaId != 0)
            {
                Response.Cookies.Append("cinemaId", CinemaId.ToString());
            }
            if (CinemaId == 0)
            {
                CinemaId = int.Parse(Request.Cookies["cinemaId"]);
            }

            int itemsNum = 4;
            int totalMovies = cinemaMovieRepository.Get(include: [m => m.Movie, c => c.Cinema], 
                where: e => e.CinemaId == CinemaId).Count();
            int totalPages = (int)Math.Ceiling(totalMovies / (double)itemsNum);
            if (pageNumber < 1)
                pageNumber = 1;
            else if (pageNumber > totalPages)
                return RedirectToAction("NotFound", "Errors");

            ViewBag.pageNumber = pageNumber;
            ViewBag.totalPages = totalPages;

            var movies = cinemaMovieRepository.Get(include: [m => m.Movie, c => c.Cinema], 
                where: e => e.CinemaId == CinemaId);
            return View(movies);
        }

        public IActionResult Filter()
        {

            var categories = categoryRepository.Get(tracked: false);
            ViewBag.Categories = categories;

            var cinemas = cinemaRepository.Get(tracked: false);
            ViewBag.Cinemas = cinemas;
            var movies = new List<Movie>();

            return View(movies);
        }

        [HttpPost]
        public IActionResult Filter(int CategoryId, int CinemaId, MovieStatus AvailabilityId)
        {

            var movie = movieRepository.GetMoviesByFilter(CategoryId, CinemaId, AvailabilityId);
            var categories = categoryRepository.Get(tracked: false);
            ViewBag.Categories = categories;

            var cinemas = cinemaRepository.Get(tracked: false);
            ViewBag.Cinemas = cinemas;
            if (movie.Any())
            {
                // add the result in the same page
                return View(movie);
            }
            else
            {
                // If there is no movie have the user needs, send him the temp data
                TempData["NotFound"] = "Sorry we cant found Movie like that";
                return RedirectToAction("Filter");
            }
        }


        public IActionResult Actor(int actorId)
        {
            var actor = actorRepository.GetOne(where: a => a.Id == actorId);
            return View(actor);
        }

        public IActionResult ActorMovies(int actorId)
        {
            var movie = movieRepository.Get(include: [a => a.Category, m => m.ActorMovies],
                where: e => e.ActorMovies.Any(a => a.ActorId == actorId));
            return View(movie);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }



        // Method to tell the JS what movie in the wishlist and what not
        private async Task SetUserWishlist()
        {
            var user = await userManager.GetUserAsync(User);
            if (user != null)
            {
                var wishlist = wishlistRepository.Get(include: [m => m.Movie], where: w => w.UserId == user.Id).ToList();
                ViewBag.Wishlist = wishlist.Select(w => w.MovieId).ToList();
            }
        }


    }
}

E-Ticket/Areas/Customer/Controllers/WishlistController.cs
using E_Ticket.Models;
using E_Ticket.Repository.IRepository;
using E_Ticket.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace E_Ticket.Controllers
{
    [Area("Customer")]
    [Authorize(Roles = $"{SD.CustomerRole}, {SD.AdminRole}")]
    public class WishlistController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly IRepository<Wishlist> wishlistRepository;

        public WishlistController(UserManager<IdentityUser> userManager, IRepository<Wishlist> WishlistRepository)
        {
            this.userManager = userManager;
            wishlistRepository = WishlistRepository;

        }

        
        public async Task<IActionResult> AddToWishlist(int movieId)
        {
            
            var user = await userManager.GetUserAsync(User);
            if (user != null)
            {
                var cartCheck = wishlistRepository.Get(where: e => e.MovieId == movieId && e.UserId == user.Id);
                if (!cartCheck.Any())
                {
                    var wishlistItem = new Wishlist { UserId = user.Id, MovieId = movieId };
                    wishlistRepository.Create(wishlistItem);
                    wishlistRepository.Commit();
                    TempData["success"] = $"Movie added to wishlist successfully!";
                    return Json(new { success = true, redirectTo = Url.Action("Index", "Home") });
                }
                return Json(new { success = false, message = "This movie is already in the wishlist." });
            }
            return NotFound();
        }

        public async Task<IActionResult> ViewWishlist()
        {
            var user = await userManager.GetUserAsync(User);
            if (user != null)
            {
                var wishlist = wishlistRepository.Get(include: [m => m.Movie], where: w => w.UserId == user.Id);
                return View(wishlist);
            }
            return NotFound();
        }
        
        public IActionResult RemoveFromWishlist(int wishlistId)
        {
            var wishlistItem = wishlistRepository.GetOne(where: e=>e.WishlistId == wishlistId);
            if (wishlistItem != null)
            {
                wishlistRepository.Delete(wishlistItem);
            }
            wishlistRepository.Commit();

            return RedirectToAction("ViewWishlist");
        }

    }
}

E-Ticket/Areas/Customer/Views/Home/Actor.cshtml
@model Actor

@{
    ViewData["Title"] = Model.FullName;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card" style="width: 100%;">
    <div class="card-body">
        <img src="/images/cast/@Model.ProfilePicture" width="60" /> <br />
        <h4>@Model.FullName</h4>
        <hr />
        <div class="card-body">
            <p class="card-text"> <strong>Bio </strong> :@Model.Bio</p>
            <p class="card-text"> <strong>News </strong>: @Model.News</p>
        </div>
        <div class="card-button">
            <a href="">Social Media</a>
            <a href="/Customer/Home/ActorMovies?actorId=@Model.Id">All movies of @Model.FullName</a>
        </div>
    </div>
</div>

E-Ticket/Areas/Customer/Views/Home/ActorMovies.cshtml
@model ICollection<Movie>


<div class="cards-wrap">
    @foreach (var item in Model)
    {

        <div class="card mb-3 pb-4" style="max-width: 540px;">
            <div class="row g-0">
                <div class="card-header">
                    <h5 class="card-title">@item.Name</h5>
                </div>

                <div class="col-md-4">
                    <img src="~/images/movies/@item.ImgUrl" class="img-fluid  card-img" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">Price: <span class="badge text-bg-dark" style="background-color:gray;">@item.Price</span></p>
                        <p class="card-text">Start Date: @item.StartDate.ToString("MMMM dd, yyyy")</p>
                        <p class="card-text">End Date: @item.EndDate.ToString("MMMM dd, yyyy")</p>
                        <p class="card-text">Category: @item.Category.Name</p>

                        <span class="badge badge-primary card-text" style=" padding:10px 15px;"> @item.MovieStatus</span>

                    </div>
                    <div class="card-button">

                        <a href="/Customer/Home/Details?movieId=@item.Id" class="btn btn-outline-secondary">More Details</a>
                        <a href="/Customer/Carts/AddToCart?movieId=@item.Id" id="bookBtn-@item.Id" class="btn btn-success book-btn"
                           data-moviestatus="@((int)item.MovieStatus)">Book Ticket</a>

                    </div>
                </div>
            </div>
        </div>
    }
</div>



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $(".book-btn").each(function () {
            var movieStatus = $(this).data("moviestatus");
            if (movieStatus == 2) {
                $(this).removeClass("btn-success").addClass("btn-danger disabled").text("Expired").prop("disabled", true);
            }
        });
    });
</script>

E-Ticket/Areas/Customer/Views/Home/Categories.cshtml
@model ICollection<Category>
@{
    ViewData["Title"] = "Categories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Categories</h2>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Name
                </td>

                <td>
                    <a href="/Customer/Home/CategoryMovies?categoryId=@item.Id">All Movies</a>
                </td>
            </tr>
        }
    </tbody>
</table>

E-Ticket/Areas/Customer/Views/Home/CategoryMovies.cshtml
@model ICollection<Movie>

<div class="cards-wrap">
    @foreach (var item in Model)
    {
        @await Html.PartialAsync("_ViewCards", item)
    }
</div>



<div>
    <hr />
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center mt-3">
            <li class="page-item @(ViewBag.pageNumber <= 1 ? "disabled":"")">
                <a class="page-link" href="?pageNumber=@(ViewBag.pageNumber - 1)" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            @for (int i = 1; i <= ViewBag.totalPages; i++)
            {
                <li class="page-item @(i == ViewBag.pageNumber ? "active" : "")">
                    <a class="page-link" href="?pageNumber=@i">@i</a>
                </li>
            }
            <li class="page-item @(ViewBag.pageNumber >= ViewBag.totalPages ? "disabled" : "")">
                <a class="page-link" href="?pageNumber=@(ViewBag.pageNumber + 1)" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $(".book-btn").each(function () {
            var movieStatus = $(this).data("moviestatus");
            if (movieStatus == 2) {
                $(this).removeClass("btn-success").addClass("btn-danger disabled").text("Expired").prop("disabled", true);
            }
        });
    });
</script>

E-Ticket/Areas/Customer/Views/Home/Details.cshtml
@model Movie
@{
    var wishlist = ViewBag.Wishlist as List<int>;
    var isInWishlist = wishlist != null && wishlist.Contains(Model.Id);
}

<hr />
<div class="d-flex justify-content-between text-center">
    <h3>Details of @Model.Name</h3>
    <div>
        <span class="badge text-bg-dark av-badge">Tickets Remaining: @Model.TicketsRemaining</span>
        <span class="badge text-bg-dark av-badge"> @Model.MovieStatus</span>
        @if (User.Identity.IsAuthenticated)
        {
            <a href="#" class="dtl-str @(isInWishlist ? "golden-star" : "")" data-movie-id="@Model.Id">
                <i class="bi bi-star-fill "></i>
            </a>
        }
    </div>
</div>
<hr />
<div class="card mb-3" style="max-width: 100%;">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="~/images/movies/@Model.ImgUrl" class="img-fluid rounded" alt="...">
        </div>
        <div class="col-md-8 pb-3">
            <div class="card-body ">
                <p class="card-text">Description: @Model.Description </p>
                <p class="card-text">Price: <span class="badge text-bg-dark" style="background-color:gray;">@Model.Price</span></p>


                <div class="" style="width: 15rem;" >
                    <div class="card-header " style="background:rgba(65, 105, 225, 0.9);">
                        Cinemas
                    </div>
                    <ul class="list-group-flush" style="padding-left:0px;">
                        @foreach (var item in Model.CinemaMovies)
                        {
                            <li class="list-group-item"  >- @item.Cinema.Name</li>
                        }
                    </ul>
                </div>

                <p class="card-text">Start Date: @Model.StartDate.ToString()</p>
                <p class="card-text">End Date: @Model.EndDate.ToString()</p>
                <p class="card-text">Category: @Model.Category.Name</p>
                @foreach (var item in Model.ActorMovies)
                {
                    <a href="/Customer/Home/Actor?actorId=@item.ActorId"><img src="~/images/cast/@item.Actor.ProfilePicture" style="width:45px;" /></a>
                }
                <p><small>Trailer</small></p>
                <video width="300" height="180" controls>
                    <source src="@Model.TrailerUrl" type="video/mp4">
                </video>
            </div>
            <div class="card-button">



                <a href="/Customer/Carts/AddToCart?movieId=@Model.Id" class="btn btn-success book-btn" data-moviestatus="@((int)@Model.MovieStatus)">Book Ticket</a>
            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $(".book-btn").each(function () {
            var movieStatus = $(this).data("moviestatus");
            if (movieStatus == 2) {
                $(this).removeClass("btn-success").addClass("btn-danger disabled").text("Expired").prop("disabled", true);
            }
        });
    });
</script>


<script>
    $(document).ready(function () {
        $('.dtl-str').on('click', function (event) {
            event.preventDefault();
            const movieId = $(this).data('movie-id');
            const starElement = $(this);

            $.ajax({
                url: '@Url.Action("AddToWishlist", "Wishlist")',
                type: 'POST',
                data: { movieId: movieId },
                success: function (response) {
                    if (response.success) {
                        starElement.toggleClass('golden-star');
                        toastr.success('Movie added to wishlist successfully!');
                    } else {
                        toastr.info(response.message);
                    }
                },
                error: function () {
                    toastr.error('An error occurred while adding the movie to the wishlist.');
                }
            });
        });
    });
</script>

E-Ticket/Areas/Customer/Views/Home/Index.cshtml
@model ICollection<Movie>
@{
    ViewData["Title"] = "Home Page";
    bool showStar;
    if (User.Identity.IsAuthenticated)
    {
        showStar = true;
    }
    else
    {
        showStar = false;
    }
}

@* Partial for the view of the movie *@
<div class="cards-wrap">
    @foreach (var item in Model)
    {
        @await Html.PartialAsync("_ViewCards", item, new ViewDataDictionary(ViewData) { { "ShowStar", showStar } })
    }
</div>


<div>
    <hr />
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center mt-3">
            <li class="page-item @(ViewBag.pageNumber <= 1 ? "disabled":"")">
                <a class="page-link" href="?pageNumber=@(ViewBag.pageNumber - 1)" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            @for (int i = 1; i <= ViewBag.totalPages; i++)
            {
                <li class="page-item @(i == ViewBag.pageNumber ? "active" : "")">
                    <a class="page-link" href="?pageNumber=@i">@i</a>
                </li>
            }
            <li class="page-item @(ViewBag.pageNumber >= ViewBag.totalPages ? "disabled" : "")">
                <a class="page-link" href="?pageNumber=@(ViewBag.pageNumber + 1)" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>


@* java script code to make the button of booking disabled and red in case the movie status is Expired *@
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $(".book-btn").each(function () {
            var movieStatus = $(this).data("moviestatus");
            if (movieStatus == 2) {
                $(this).removeClass("btn-success").addClass("btn-danger disabled").text("Expired").prop("disabled", true);
            }
        });
    });
</script>

<script>
    $(document).ready(function () {
        $('.card-star').on('click', function (event) {
            event.preventDefault();
            const movieId = $(this).data('movie-id');
            const starElement = $(this);

            $.ajax({
                url: '@Url.Action("AddToWishlist", "Wishlist")',
                type: 'POST',
                data: { movieId: movieId },
                success: function (response) {
                    if (response.success) {
                        starElement.toggleClass('golden-star');
                        toastr.success('Movie added to wishlist successfully!');
                    } else {
                        toastr.info(response.message);
                    }
                },
                error: function () {
                    toastr.error('An error occurred while adding the movie to the wishlist.');
                }
            });
        });
    });
</script>

E-Ticket/Areas/Customer/Views/Home/Search.cshtml
@model ICollection<Movie>

@{
    bool showStar;
    if (User.Identity.IsAuthenticated)
    {
        showStar = true;
    }
    else
    {
        showStar = false;
    }
}

<h3>Search Result:-</h3>
<hr />

<div class="cards-wrap">
    @foreach (var item in Model)
    {
        @await Html.PartialAsync("_ViewCards", item, new ViewDataDictionary(ViewData) { { "ShowStar", showStar } })
    }
</div>



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $(".book-btn").each(function () {
            var movieStatus = $(this).data("moviestatus");
            if (movieStatus == 2) {
                $(this).removeClass("btn-success").addClass("btn-danger disabled").text("Expired").prop("disabled", true);
            }
        });
    });
</script>



<script>
    $(document).ready(function () {
        $('.card-star').on('click', function (event) {
            event.preventDefault();
            const movieId = $(this).data('movie-id');
            const starElement = $(this);

            $.ajax({
                url: '@Url.Action("AddToWishlist", "Wishlist")',
                type: 'POST',
                data: { movieId: movieId },
                success: function (response) {
                    if (response.success) {
                        starElement.toggleClass('golden-star');
                        toastr.success('Movie added to wishlist successfully!');
                    } else {
                        toastr.info(response.message);
                    }
                },
                error: function () {
                    toastr.error('An error occurred while adding the movie to the wishlist.');
                }
            });
        });
    });
</script>